definitions:
  Models.User:
    properties:
      address:
        type: string
      email:
        type: string
      id:
        type: integer
      name:
        type: string
      phone:
        type: string
    type: object
info:
  contact: {}
paths:
  /users:
    post:
      consumes:
      - application/json
      description: create a User from the payload.
      parameters:
      - description: Add a User
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/Models.User'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/Models.User'
        "400":
          description: Bad Request
          schema:
            type: string
  /users/{uuid}:
    get:
      consumes:
      - application/json
      description: get user by id
      parameters:
      - description: Some ID
        in: path
        name: uuid
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: ok
          schema:
            $ref: '#/definitions/Models.User'
        "400":
          description: We need ID!!
          schema:
            type: string
        "404":
          description: Can not find ID
          schema:
            type: string
swagger: "2.0"
